### ISSUE TITLE
cmd.js line 219 cannot call forEach on undefined while using -u channel

### ISSUE THREAD

**Issue by kylebeth94** [juanpabloaj/node-slack-cli#2]
TypeError: Cannot call method 'forEach' of undefined
    at Array.async.auto.channelId [as 1](/usr/local/lib/node_modules/slack-cli/bin/cmd.js:219:27)
    at listener (/usr/local/lib/node_modules/slack-cli/node_modules/async/lib/async.js:490:46)
    at /usr/local/lib/node_modules/slack-cli/node_modules/async/lib/async.js:441:17
    at _each (/usr/local/lib/node_modules/slack-cli/node_modules/async/lib/async.js:46:13)
    at Object.taskComplete (/usr/local/lib/node_modules/slack-cli/node_modules/async/lib/async.js:440:13)
    at processImmediate [as _immediateCallback](timers.js:330:15)

**Comment by juanpabloaj** [comment]
@kylebeth94 you try something similar to 

```
 slack -c slackChannelName -m "message to send"
```

?

**Comment by sherbie** [comment]
I am getting the same error when run in travis-ci:

/home/travis/build/[...]/node_modules/slack-cli/bin/cmd.js:219
            pipe.channels.forEach(function (v, i) {
                          ^
TypeError: Cannot call method 'forEach' of undefined
    at Array.async.auto.channelId [as 1](/home/travis/build/[...]/node_modules/slack-cli/bin/cmd.js:219:27)
    at listener (/home/travis/build/[...]/node_modules/slack-cli/node_modules/async/lib/async.js:490:46)
    at /home/travis/build/[...]/node_modules/slack-cli/node_modules/async/lib/async.js:441:17
    at _each (/home/travis/build/[...]/node_modules/slack-cli/node_modules/async/lib/async.js:46:13)
    at Object.taskComplete (/home/travis/build/[...]/node_modules/slack-cli/node_modules/async/lib/async.js:440:13)
    at processImmediate [as _immediateCallback](timers.js:354:15)

from the following command:

`slackcli -t my-token -u "Travis CI" -m "Results for build are located at: ${url}" -h my-channel`

**Comment by veksen** [comment]
Same issue, node 5.1.0

**Comment by juanpabloaj** [comment]
@veksen I try with node 5.10 

```
$ node --version
v5.1.0
```

and I don't have problems 

```
slack -c logs -m "hello world" -u "Travis CI"
```

this command work fine for me.

**Comment by juanpabloaj** [comment]
@sean-Unity are you using `node-slack-cli` package? the command is `slack` no `slackcli`

**Comment by kylebeth94** [comment]
I figured out the issue that I was having. Just a stupid mistake on my end.

**Comment by exitjones** [comment]
please feel free to enable others to learn from your mistakes (no matter how stupid).

**Comment by sherbie** [comment]
@kylebeth94 What was the mistake you made and how did you resolve it?

**Comment by kylebeth94** [comment]
I originally installed a very similar client that was named slack-cli instead of node-slack-cli. I somehow mixed up the documentation pages when going back to automate it for a Reddit bot
